import { Head } from '@inertiajs/react'
import AppLayout from '@/Components/Layout/AppLayout'
import AnalysisHistory from '@/Components/Analysis/AnalysisHistory'
import type { AnalysisRun } from '@/types'

interface AnalysisProps {
    analyses: AnalysisRun[]
}

export default function Analysis({ analyses }: AnalysisProps) {
    return (
        <AppLayout>
            <Head title="Analysis" />
            <h1 className="mb-6 text-2xl font-bold text-gray-900">
                Spending Analysis
            </h1>

            <div className="mb-8 rounded-lg border border-indigo-200 bg-indigo-50 p-6">
                <h2 className="mb-2 text-lg font-semibold text-gray-900">
                    Run analysis with your Claude client
                </h2>
                <p className="text-sm text-gray-700">
                    Analyses are now generated by your own Claude client over
                    MCP. Connect Claude (see the{' '}
                    <a
                        href="/privacy"
                        className="font-medium text-indigo-700 underline"
                    >
                        Privacy &amp; MCP
                    </a>{' '}
                    page), then run the{' '}
                    <code className="rounded bg-white px-1 py-0.5 text-indigo-700">
                        analyze_spending
                    </code>{' '}
                    prompt. Saved results appear below.
                </p>
            </div>

            <div className="rounded-lg border border-gray-200 bg-white">
                <div className="border-b border-gray-200 px-6 py-4">
                    <h2 className="text-lg font-semibold text-gray-900">
                        Analysis History
                    </h2>
                </div>
                <AnalysisHistory analyses={analyses} />
            </div>
        </AppLayout>
    )
}
